### ISSUE TITLE
✨ Make CURLable

### ISSUE THREAD

**Issue by ThatOneCalculator** [zer0bin-dev/zer0bin#30]
## Summary

Perhaps this could deprecate the client

**Comment by idanoo** [comment]
A little work around I'm using for now. It just requires jq for json parsing

`curl -sS 'https://tinker.nz/api/p/OPF7x8sB' | jq -r .data.content`

**Comment by idanoo** [comment]
A little work around I'm using for now. It just requires jq for json parsing

curl -sS 'https://<zer0bin URL>/api/p/<pasteID>' | jq -r .data.content

**Comment by idanoo** [comment]
A little work around I'm using for now. It just requires jq for json parsing

curl -sS 'https://tinker.nz/api/p/aBcDeFgH' | jq -r .data.content
