### ISSUE TITLE
Debian Bullseye 'main' panicked at 'Failed to load config: Os 🐛 

### ISSUE THREAD

**Issue by DrSkyfaR** [zer0bin-dev/zer0bin#46]
## 💡 Summary
zer0bin does not start

## 🥰 Expected Behavior

> /zer0bin/backend/target/release$ ./zer0bin-bin
> thread 'main' panicked at 'Failed to load config: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/config.rs:45:33
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## 📝 Steps to Reproduce

1.
2.
3.

## 📌 Environment

zer0bin version: 1.02

Your OS: Debian Bullseye
Your browser: Firefox

I hope someone can help me with this Problem :)

**Comment by ThatOneCalculator** [comment]
The message clearly says "failed to load config". Please actually follow the self host instructions in the Wiki, which includes making the config file.
