### ISSUE TITLE
🤔 replace Cartograph CF with a free font

### ISSUE THREAD

**Issue by nullobsi** [zer0bin-dev/zer0bin#58]
I realize there is already a note about this in the repository. However, it simply messes with those who host without realizing they are using a font without a proper license. The font could be added in locally.

**Comment by ThatOneCalculator** [comment]
People have been pirating Cartograph CF for god-knows-how-long by now. If they want to use a diff font, they can modify the files.

**Comment by ThatOneCalculator** [comment]
@nullobsi in regards to this -- I added the option to use Fira Code by cloning then running 
```
cd frontend/style
mv font-fira.scss font.scss
```
