### ISSUE TITLE
🐛 3 Mobile Complications; Crash Prone

### ISSUE THREAD

**Issue by insyri** [zer0bin-dev/zer0bin#62]
## 💡 Summary

The site on a mobile interface serves many complications. These are some that I have collected throughout using zer0bin. All of these happen on their own with no real direct way of reproducing other than just using it. Most of my pastes are around 4000 characters, see Steps to Reproduce.

- [ ] Text unselectable horizontal of context (top right) box.
- [ ] Save button does not register for an amount of time.
- [ ] Crashes browser often on page load/scroll and pre-confetti load.

## 🥰 Expected Behavior

Selection on specified area with no issues.

Responsive save button.

No lag or site-wide/browser wide crashes.

## 🤬 Actual Behavior

Selecting text to the left side of the context box, matching the height, will become unselectable.

Save button pressed but does not register until a minute later, with element spam on UI creating lag along with confetti.

Often following said above, site becomes unresponsive for a moment before loading a lagful ammount of confetti.

## 📝 Steps to Reproduce

1. Visit paste on mobile with about 4000 characters, [what I used](https://zer0b.in/0vV77z_4).
2. Attempt basic usage on site: scrolling, selecting, interaction with buttons.
3. 2 but browser.

## 📌 Environment

zer0bin version: Production as of right now; v1.1.1(?)
Your OS: Android 11
Your browser: Chrome

**Comment by insyri** [comment]
Additional note: 1 second lag is normal for a copy/paste text of that length, never has been more for other sites.

This may be a phone specific problem, but I think against this due to said phone being recent with happenings of these degrees.

**Comment by ThatOneCalculator** [comment]
We're working on a site redesign right now, but the current site shouldn't be causing ***crashes*** by any means. What phone do you have? Are you sure something isn't using up performance in the background?

**Comment by insyri** [comment]
Motorola G Power, 2021. Everything said was the only thing running. I even closed all other Chrome tabs.

**Comment by insyri** [comment]
Alright, I'll close this issue since the UI is being reworked anyways. Thanks!
