### ISSUE TITLE
🚀 

### ISSUE THREAD

**Issue by marsupialgutz** [zer0bin-dev/zer0bin#63]
## Details

- Domain name: https://zbin.possums.xyz
- What country is the server in: USA
- What server hardware/provider is the server on: Local hardware (old laptop)
- Are you using CloudFlare or any Google services (domain, DNS, etc): Cloudflare for domain + DNS
- What version of zer0bin is it running: v1.1.1
- Have you made any modifications to zer0bin? If so, what?: None
- What are the ratelimits: 2 seconds between pastes, 5 pastes allowed before limiting
- What is the expiration time of pastes: 180 days
- What is the max paste size: 75000 chars

**Comment by ThatOneCalculator** [comment]
Will add when i get home
