### ISSUE TITLE
🚀 

### ISSUE THREAD

**Issue by soopyc** [zer0bin-dev/zer0bin#66]
## Details

- Domain name: https://p.soopy.moe
- What country is the server in: 🇭🇰 Hong Kong 
- What server hardware/provider is the server on: Personal infrastructure (old pc)
- Are you using CloudFlare or any Google services (domain, DNS, etc): Cloudflare DNS, proxy disabled.
- What version of zer0bin is it running: 1.1.1
- Have you made any modifications to zer0bin? If so, what?: none
- What are the ratelimits: 2 seconds between pastes, 5 pastes before getting 429'd
- What is the expiration time of pastes: 365 days
- What is the max paste size: 75k char limit

**Comment by ThatOneCalculator** [comment]
Added to readme!
