### ISSUE TITLE
🚀 

### ISSUE THREAD

**Issue by nixgoat** [zer0bin-dev/zer0bin#73]
## Details

- Domain name: paste.mint.lgbt
- What country is the server in:  Chile
- What server hardware/provider is the server on: Dedicated
- Are you using CloudFlare or any Google services (domain, DNS, etc): No
- What version of zer0bin is it running: v1.1.1
- Have you made any modifications to zer0bin? If so, what?: No
- What are the ratelimits: 2 seconds in-between pastes, 5 allowed pastes before ratelimit
- What is the expiration time of pastes: 30 days
- What is the max paste size: 50000 characters

**Comment by ThatOneCalculator** [comment]
Added, although this project is basically dead :P

**Comment by wiredsis** [comment]
Sad, this one is good :<
